# Generated by Django 2.1.4 on 2019-08-19 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_auto_20190817_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamrequest',
            old_name='description',
            new_name='essay',
        ),
    ]
