# Generated by Django 2.1.4 on 2019-09-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_auto_20190819_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamrequest',
            name='essay',
            field=models.CharField(max_length=500, verbose_name='request reason'),
        ),
    ]
