# Generated by Django 2.1.4 on 2019-09-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0004_auto_20190902_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='graduation_year',
        ),
        migrations.AddField(
            model_name='participant',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
