# Generated by Django 2.1.4 on 2019-09-11 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0005_auto_20190906_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamrequest',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.Participant', verbose_name='participant'),
        ),
    ]
